version: '3'
services:
  nodeR:
    image: blkchn
    command: blkchn -v -h 1000 -ws 2000
    ports:
      - '1000:1000'
      - '2000:2000'
  node1:
    image: blkchn
    command: blkchn -v -i nodeR:1000 -h 1001 -ws 2001
    ports:
      - '1001:1001'
      - '2001:2001'
    depends_on:
      - nodeR
  node2:
    image: blkchn
    command: blkchn -v -i node1:1001 -h 1002 -ws 2002
    ports:
      - '1002:1002'
      - '2002:2002'
    depends_on:
      - node1
