version: '3'
services:
  cli1:
    image: blkchn
    command: blockchain -v -hport 1000 -wsport 2000
    ports:
     - '1000:1000'
     - '2000:2000'
  cli2:
      image: blkchn
      command: blockchain -v -ipeer localhost:1000 -hport 1001 -wsport 2001
      ports:
       - '1001:1001'
       - '2001:2001'
  cli3:
      image: blkchn
      command: blockchain -v -ipeer localhost:1001 -hport 1002 -wsport 2002
      ports:
       - '1002:1002'
       - '2002:2002'
