version: '3'
services:
  nodeR:
    image: blkchn
    command: blkchn -v -h 0918 -ws 0919
    ports:
      - '0918:0918'
      - '0919:0919'
  node1:
    image: blkchn
    command: blkchn -v -i nodeR:0918 -h 0928 -ws 0929
    ports:
      - '0928:0928'
      - '0929:0929'
    depends_on:
      - nodeR
  node2:
    image: blkchn
    command: blkchn -v -i node1:0928 -h 0938 -ws 0939
    ports:
      - '0938:0938'
      - '0939:0939'
    depends_on:
      - node1
